# .travis.yml for R projects.
# See https://docs.travis-ci.com/user/languages/r/

language: r
r: bioc-release
cache: packages
sudo: false

bioc_packages:
 - sva
 - genefilter

r_github_packages:
 - jimhester/covr
after_success:
 - Rscript -e 'covr::codecov()'
